---

- name: Create directory for backup data.
  file:
    path: "{{ backup_data }}"
    state: directory
    mode: '0755'

- name: Create directory for Mongo backup.
  file:
    path: "{{ mongo_backup }}"
    state: directory
    mode: '0777'

- name: Create directory for Rocketchat backup.
  file:
    path: "{{ rocketchat_backup }}"
    state: directory
    mode: '0777'

- name: Configure Mongo backup script.
  template:
    src: mongo-backup.sh.j2
    dest: "{{ backup_data }}/mongo-backup.sh"
    mode: 'u+rwx'

- name: Configure cron for hourly Mongo backups.
  cron:
    minute: "0"
    hour: "*"
    name: mongo_backup
    job: |
      {{ backup_data }}/mongo-backup.sh

- name: Configure cron for hourly Rocketchat backups.
  cron:
    minute: "0"
    hour: "*"
    name: rocketchat_backup
    job: |
      docker exec `docker ps -q --filter ancestor=rocketchat/rocket.chat:{{ rocketchat_image_version }}` bash -c 'tar -zcvf /backup/app-$(date +\%Y-\%m-\%d_\%Hh\%Mm\%Ss).tar.gz /app'

- name: Clean up old Mongo backups once per day.
  cron:
    minute: "10"
    hour: "1"
    name: mongo_backup_cleanup
    job: |
      find {{ mongo_backup }}/* -mtime +{{ backup_retention_days }} -exec rm -rf {} \;

- name: Clean up old Rocketchat backups once per day.
  cron:
    minute: "20"
    hour: "1"
    name: rocketchat_backup_cleanup
    job: |
      find {{ rocketchat_backup }}/* -mtime +{{ backup_retention_days }} -exec rm -rf {} \;
