---

- name: Create directory for Docker container data.
  file:
    path: "{{ docker_data }}"
    state: directory
    mode: '0755'

- include_tasks: mongo-setup.yml
- include_tasks: rocketchat-setup.yml
- include_tasks: swag-setup.yml

- include_tasks: compose.yml
