---

- name: Create directory for Docker container data.
  file:
    path: "{{ docker_data }}"
    state: directory
    mode: '0755'

- include_tasks: mongo-setup.yml
- include_tasks: rocketchat-setup.yml
- include_tasks: swag-setup.yml

- include_tasks: compose.yml

- include_tasks: backup.yml

- name: Configure nightly docker-compose update cron.
  cron:
    minute: "20"
    hour: "2"
    name: docker_compose_pull
    job: |
      cd /data/docker-compose && docker-compose pull && docker-compose up -d
