---
# TODO: Create mongo-specific user

- name: Create directory for Mongo container data.
  file:
    path: "{{ mongo_data }}"
    state: directory
    mode: '0755'

- name: Create directory for Mongo container data (DB).
  file:
    path: "{{ mongo_data }}/data/db"
    state: directory
    mode: '0755'

- name: Create directory for Mongo container data (dump).
  file:
    path: "{{ mongo_data }}/data/dump"
    state: directory
    mode: '0755'

- name: Create the Mongo docker container.
  docker_container:
    name: mongo
    image: mongo:4.4
    command: mongod --oplogSize 128 --replSet rs0 --storageEngine=wiredTiger
    restart_policy: unless-stopped
    volumes:
      - "{{ mongo_data }}/data/db:/data/db"
      - "{{ mongo_data }}/data/dump:/dump"
    published_ports:
      - "27017"
    networks:
      - name: docker-net

- name: Create the Mongo replica set.
  docker_container:
    name: mongo-init-replica
    image: mongo:4.4
    command: >
      bash -c
        "for i in `seq 1 30`; do
          mongo mongo/rocketchat --eval \"
            rs.initiate({
              _id: 'rs0',
              members: [ { _id: 0, host: 'localhost:27017' } ]})\" &&
          s=$? && break || s=$?;
          echo \"Tried $i times. Waiting 5 secs...\";
          sleep 5;
        done; (exit $s)"
    networks:
      - name: docker-net
        links:
          - mongo
