---
# TODO: Create swag-specific user

- name: Create directory for swag container data.
  file:
    path: "{{ swag_data }}"
    state: directory
    mode: '0755'

- name: Create the Rocket.Chat docker container.
  docker_container:
    name: sawg
    image: linuxserver/swag
    command: 
    capabilities:
      - net_admin
    restart_policy: unless-stopped
    volumes:
      - "{{ rocketchat_data }}/uploads:/app/uploads"
    env:
      TZ: "America/Los_Angeles"
      URL: ""
    published_ports:
      - "3000"
    networks:
      - name: docker-net
        links:
          - mongo
